# 参考 https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml
# 模式 规则
mode: rule
# 静默，不输出
log-level: silent
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
ipv6: false
# TCP 并发连接所有 IP, 将使用最快握手的 TCP
tcp-concurrent: true
# 此时 Clash 发现并关闭一个无效 TCP 连接用时： 1*keep-alive-interval + 9*keep-alive-interval
keep-alive-interval: 30
# 更换延迟计算方式，去除握手等额外延迟
unified-delay: true
# GEO 文件加载模式 standard：标准加载器  memconservative：专为内存受限 (小内存) 设备优化的加载器 (默认值)
geodata-loader: standard
# 更改 geoip 使用文件，mmdb 或者 dat，可选 true/false,true为 dat，此项有默认值 false, mmdb效率更高
geodata-mode: false
# 域名嗅探
sniffer:
  # 是否启用sniffer
  enable: true
  # 对 redir-host 类型识别的流量进行强制嗅探
  force-dns-mapping: true
  # 对所有未获取到域名的流量进行强制嗅探
  parse-pure-ip: true
  # 是否使用嗅探结果作为实际访问，默认为 true
  override-destination: true
dns:
  # 开启dns劫持
  enable: true
  # 开启 DoH 支持 HTTP/3，将并发尝试
  prefer-h3: true
  enhanced-mode: fake-ip
  # 禁用ipv6
  ipv6: false
  # 查询 hosts
  use-hosts: true
  # 用于解析 nameserver，fallback 以及其他 DNS 服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
    - tls://9.9.9.9:853
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - https://9.9.9.9/dns-query
  # DNS 主要域名配置
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver:
    - tls://dns.alidns.com
    - tls://dot.pub
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  # 当配置 fallback 时，会查询 nameserver 中返回的 IP 是否为 CN，非必要配置
  # 当不是 CN，则使用 fallback 中的 DNS 查询结果
  # 确保配置 fallback 时能够正常查询
  fallback:
    - tls://dns.google
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tls://dns.quad9.net
    - tls://dns.adguard-dns.com
    - tls://dns.opendns.com
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://doh.opendns.com/dns-query
  # 专用于节点域名解析的 DNS 服务器，非必要配置项
  proxy-server-nameserver:
    - tls://dns.alidns.com
    - tls://dot.pub
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - tls://dns.google
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tls://dns.quad9.net
    - tls://dns.adguard-dns.com
    - tls://dns.opendns.com
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://doh.opendns.com/dns-query
  # 使用dns的策略
  nameserver-policy:
    #geosite查询出来的国内、局域网、苹果使用国内的dns
    geosite:cn,private,apple:
      - tls://dns.alidns.com
      - tls://dot.pub
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    # geosite查询出来的国外,长城名单使用国外的dns
    geosite:geolocation-!cn,gfw:
      - tls://dns.google
      - tls://1dot1dot1dot1.cloudflare-dns.com
      - tls://dns.quad9.net
      - tls://dns.adguard-dns.com
      - tls://dns.opendns.com
      - https://dns.google/dns-query
      - https://dns.cloudflare.com/dns-query
      - https://dns.quad9.net/dns-query
      - https://dns.adguard-dns.com/dns-query
      - https://doh.opendns.com/dns-query
  # 配置 fallback 使用条件
  fallback-filter:
    # 配置是否使用 geoip
    geoip: true
    # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
    geoip-code: CN
    # 当 nameserver 域名的 IP 是下面的网段,使用 fallback 中的 DNS 查询结果
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
    # 下面的域名使用 fallback 中的 DNS 查询结果
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.twitter.com'
      - '+.youtube.com'
      - '+.xn--ngstr-lra8j.com'
      - '+.google.cn'
      - '+.googleapis.cn'
      - '+.googleapis.com'
      - '+.gvt1.com'
      - '+.openai.com'
      - '+.auth0.com'
      - '+.telegram.me'
      - '+.t.me'
      - '+.telegram.org'
      - '+.telesco.pe'
      - '+.netflix.com'
      - '+.netflix.net'
      - '+.nflxext.com'
      - '+.nflximg.com'
      - '+.nflxso.net'
      - '+.nflxvideo.net'
      - '+.amazonaws.com'
      - '+.amazon.com'
      - '+.github.com'
      - '+.githubusercontent.com'
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - "+.v2ex.com"
      - "+.linkedin.com"
      - "+.pubpeer.com"
      - "+.nih.gov"
      - "+.scopus.com"
      - "+.ithenticate.com"
      - "+.chatgpt.com"
  # fake-ip模式下 虚拟ip网段
  fake-ip-range: 198.18.0.1/16
  # fake-ip模式下,配置不使用 fake-ip 的域名
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - stun.*.*
    - stun.*.*.*
    - swscan.apple.com
    - mesu.apple.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.ipv6.microsoft.com"
    - teredo.*.*.*
    - teredo.*.*
    - speedtest.cros.wr.pvp.net
    - "+.jjvip8.com"
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
tun:
  enable: true
  stack: mixed
  auto-detect-interface: true
  auto-route: true
  strict-route: true
  auto-redirect: true
