port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
profile:
  tracing: true
dns:
  enable: true
  ipv6: false
  # 模式：redir-host或fake-ip
  enhanced-mode: fake-ip
  use-hosts: true
  listen: '127.0.0.1:53'
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - 223.5.5.5 # 阿里DNS
    - 180.76.76.76 # 百度DNS
    - 119.29.29.29 # 腾讯DNS
    - 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
    - 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
    - 114.114.114.114 # 114DNS
    - https://dns.alidns.com/dns-query # 阿里 DoH DNS
    - https://doh.360.cn/dns-query # 360 DoH DNS
  fallback:
    - 8.8.8.8 # 谷歌DNS
    - 1.1.1.1 # Cloudflare DNS
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net

# clash for windwos 的配置
clash-for-android:
  append-system-dns: false
cfw-proxies-order: default
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false
cfw-bypass:
  - "*.13th.tech"
  - "*.423down.com"
  - "*.bokecc.com"
  - "*.chaipip.com"
  - "*.chinaplay.store"
  - "*.hrtsea.com"
  - "*.kaikeba.com"
  - "*.laomo.me"
  - "*.mpyit.com"
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - "*.qupu123.com"
  - "*.pdfwifi.com"
  - "*.zhenguanyu.biz"
  - "*.zhenguanyu.com"
  - "*.cn"
  - "*.xn--fiqs8s"
  - "*.xn--55qx5d"
  - "*.xn--io0a7i"
  - "*360buy*"
  - "*alicdn*"
  - "*alimama*"
  - "*alipay*"
  - "*appzapp*"
  - "*baidupcs*"
  - "*bilibili*"
  - "*ccgslb*"
  - "*chinacache*"
  - "*duobao*"
  - "*jdpay*"
  - "*moke*"
  - "*qhimg*"
  - "*vpimg*"
  - "*xiami*"
  - "*xiaomi*"
  - "*.360.com"
  - "*.360kuai.com"
  - "*.360safe.com"
  - "*.dhrest.com"
  - "*.qhres.com"
  - "*.qhstatic.com"
  - "*.qhupdate.com"
  - "*.so.com"
  - "*.4399.com"
  - "*.4399pk.com"
  - "*.5054399.com"
  - "*.img4399.com"
  - "*.58.com"
  - "*.1688.com"
  - "*.aliapp.org"
  - "*.alibaba.com"
  - "*.alibabacloud.com"
  - "*.alibabausercontent.com"
  - "*.alicdn.com"
  - "*.alicloudccp.com"
  - "*.aliexpress.com"
  - "*.aliimg.com"
  - "*.alikunlun.com"
  - "*.alipay.com"
  - "*.alipayobjects.com"
  - "*.alisoft.com"
  - "*.aliyun.com"
  - "*.aliyuncdn.com"
  - "*.aliyuncs.com"
  - "*.aliyundrive.com"
  - "*.amap.com"
  - "*.autonavi.com"
  - "*.dingtalk.com"
  - "*.ele.me"
  - "*.hichina.com"
  - "*.mmstat.com"
  - "*.mxhichina.com"
  - "*.soku.com"
  - "*.taobao.com"
  - "*.taobaocdn.com"
  - "*.tbcache.com"
  - "*.tbcdn.com"
  - "*.tmall.com"
  - "*.tmall.hk"
  - "*.ucweb.com"
  - "*.xiami.com"
  - "*.xiami.net"
  - "*.ykimg.com"
  - "*.youku.com"
  - "*.baidu.com"
  - "*.baidubcr.com"
  - "*.baidupcs.com"
  - "*.baidustatic.com"
  - "*.bcebos.com"
  - "*.bdimg.com"
  - "*.bdstatic.com"
  - "*.bdurl.net"
  - "*.hao123.com"
  - "*.hao123img.com"
  - "*.jomodns.com"
  - "*.yunjiasu-cdn.net"
  - "*.acg.tv"
  - "*.acgvideo.com"
  - "*.b23.tv"
  - "*.bigfun.cn"
  - "*.bigfunapp.cn"
  - "*.biliapi.com"
  - "*.biliapi.net"
  - "*.bilibili.com"
  - "*.biligame.com"
  - "*.biligame.net"
  - "*.bilivideo.com"
  - "*.bilivideo.cn"
  - "*.hdslb.com"
  - "*.im9.com"
  - "*.smtcdns.net"
  - "*.battle.net"
  - "*.battlenet.com"
  - "*.blizzard.com"
  - "*.amemv.com"
  - "*.bdxiguaimg.com"
  - "*.bdxiguastatic.com"
  - "*.byted-static.com"
  - "*.bytedance.com"
  - "*.bytedance.net"
  - "*.bytedns.net"
  - "*.bytednsdoc.com"
  - "*.bytegoofy.com"
  - "*.byteimg.com"
  - "*.bytescm.com"
  - "*.bytetos.com"
  - "*.bytexservice.com"
  - "*.douyin.com"
  - "*.douyinpic.com"
  - "*.douyinstatic.com"
  - "*.douyinvod.com"
  - "*.feelgood.cn"
  - "*.feiliao.com"
  - "*.gifshow.com"
  - "*.huoshan.com"
  - "*.huoshanzhibo.com"
  - "*.ibytedapm.com"
  - "*.iesdouyin.com"
  - "*.ixigua.com"
  - "*.kspkg.com"
  - "*.pstatp.com"
  - "*.snssdk.com"
  - "*.toutiao.com"
  - "*.toutiao13.com"
  - "*.toutiaoapi.com"
  - "*.toutiaocdn.com"
  - "*.toutiaocdn.net"
  - "*.toutiaocloud.com"
  - "*.toutiaohao.com"
  - "*.toutiaohao.net"
  - "*.toutiaoimg.com"
  - "*.toutiaopage.com"
  - "*.wukong.com"
  - "*.zijieapi.com"
  - "*.zijieimg.com"
  - "*.zjbyte.com"
  - "*.zjcdn.com"
  - "*.cctv.com"
  - "*.cctvpic.com"
  - "*.livechina.com"
  - "*.21cn.com"
  - "*.didialift.com"
  - "*.didiglobal.com"
  - "*.udache.com"
  - "*.douyu.com"
  - "*.douyu.tv"
  - "*.douyuscdn.com"
  - "*.douyutv.com"
  - "*.epicgames.com"
  - "*.epicgames.dev"
  - "*.helpshift.com"
  - "*.paragon.com"
  - "*.unrealengine.com"
  - "*.dbankcdn.com"
  - "*.hc-cdn.com"
  - "*.hicloud.com"
  - "*.hihonor.com"
  - "*.huawei.com"
  - "*.huaweicloud.com"
  - "*.huaweishop.net"
  - "*.hwccpc.com"
  - "*.vmall.com"
  - "*.vmallres.com"
  - "*.iflyink.com"
  - "*.iflyrec.com"
  - "*.iflytek.com"
  - "*.71.am"
  - "*.71edge.com"
  - "*.iqiyi.com"
  - "*.iqiyipic.com"
  - "*.ppsimg.com"
  - "*.qiyi.com"
  - "*.qiyipic.com"
  - "*.qy.net"
  - "*.360buy.com"
  - "*.360buyimg.com"
  - "*.jcloudcs.com"
  - "*.jd.com"
  - "*.jd.hk"
  - "*.jdcloud.com"
  - "*.jdpay.com"
  - "*.paipai.com"
  - "*.iciba.com"
  - "*.ksosoft.com"
  - "*.ksyun.com"
  - "*.kuaishou.com"
  - "*.yximgs.com"
  - "*.meitu.com"
  - "*.meitudata.com"
  - "*.meitustat.com"
  - "*.meipai.com"
  - "*.le.com"
  - "*.lecloud.com"
  - "*.letv.com"
  - "*.letvcloud.com"
  - "*.letvimg.com"
  - "*.letvlive.com"
  - "*.letvstore.com"
  - "*.hitv.com"
  - "*.hunantv.com"
  - "*.mgtv.com"
  - "*.duokan.com"
  - "*.mi-img.com"
  - "*.mi.com"
  - "*.miui.com"
  - "*.xiaomi.com"
  - "*.xiaomi.net"
  - "*.xiaomicp.com"
  - "*.126.com"
  - "*.126.net"
  - "*.127.net"
  - "*.163.com"
  - "*.163yun.com"
  - "*.lofter.com"
  - "*.netease.com"
  - "*.ydstatic.com"
  - "*.youdao.com"
  - "*.pplive.com"
  - "*.pptv.com"
  - "*.pinduoduo.com"
  - "*.yangkeduo.com"
  - "*.leju.com"
  - "*.miaopai.com"
  - "*.sina.com"
  - "*.sina.com.cn"
  - "*.sina.cn"
  - "*.sinaapp.com"
  - "*.sinaapp.cn"
  - "*.sinaimg.com"
  - "*.sinaimg.cn"
  - "*.weibo.com"
  - "*.weibo.cn"
  - "*.weibocdn.com"
  - "*.weibocdn.cn"
  - "*.xiaoka.tv"
  - "*.go2map.com"
  - "*.sogo.com"
  - "*.sogou.com"
  - "*.sogoucdn.com"
  - "*.sohu-inc.com"
  - "*.sohu.com"
  - "*.sohucs.com"
  - "*.sohuno.com"
  - "*.sohurdc.com"
  - "*.v-56.com"
  - "*.playstation.com"
  - "*.playstation.net"
  - "*.playstationnetwork.com"
  - "*.sony.com"
  - "*.sonyentertainmentnetwork.com"
  - "*.cm.steampowered.com"
  - "*.steamcontent.com"
  - "*.steamusercontent.com"
  - "*.steamchina.com"
  - csgo.wmsj.cn
  - dota2.wmsj.cn
  - wmsjsteam.com
  - dl.steam.clngaa.com
  - dl.steam.ksyna.com
  - st.dl.bscstorage.net
  - st.dl.eccdnx.com
  - st.dl.pinyuncloud.com
  - steampipe.steamcontent.tnkjmec.com
  - steampowered.com.8686c.com
  - steamstatic.com.8686c.com
  - "*.foxmail.com"
  - "*.gtimg.com"
  - "*.idqqimg.com"
  - "*.igamecj.com"
  - "*.myapp.com"
  - "*.myqcloud.com"
  - "*.qq.com"
  - "*.qqmail.com"
  - "*.qqurl.com"
  - "*.smtcdns.com"
  - "*.smtcdns.net"
  - "*.soso.com"
  - "*.tencent-cloud.net"
  - "*.tencent.com"
  - "*.tencentmind.com"
  - "*.tenpay.com"
  - "*.wechat.com"
  - "*.weixin.com"
  - "*.weiyun.com"
  - "*.appsimg.com"
  - "*.appvipshop.com"
  - "*.vip.com"
  - "*.vipstatic.com"
  - "*.ximalaya.com"
  - "*.xmcdn.com"
  - "*.00cdn.com"
  - "*.88cdn.com"
  - "*.kanimg.com"
  - "*.kankan.com"
  - "*.p2cdn.com"
  - "*.sandai.net"
  - "*.thundercdn.com"
  - "*.xunlei.com"
  - "*.got001.com"
  - "*.p4pfile.com"
  - "*.rrys.tv"
  - "*.rrys2020.com"
  - "*.yyets.com"
  - "*.zimuzu.io"
  - "*.zimuzu.tv"
  - "*.zmz001.com"
  - "*.zmz002.com"
  - "*.zmz003.com"
  - "*.zmz004.com"
  - "*.zmz2019.com"
  - "*.zmzapi.com"
  - "*.zmzapi.net"
  - "*.zmzfile.com"
  - "*announce*"
  - "*torrent*"
  - "*tracker*"
  - "*.animebytes.tv"
  - "*.animetorrents.me"
  - "*.awesome-hd.me"
  - "*.beitai.pt"
  - "*.bittorrent.com"
  - "*.broadcasthe.net"
  - "*.chdbits.co"
  - "*.classix-unlimited.co.uk"
  - "*.empornium.me"
  - "*.gazellegames.net"
  - "*.hd4fans.org"
  - "*.hdchina.org"
  - "*.hdhome.org"
  - "*.hdsky.me"
  - "*.hdtime.org"
  - "*.hdzone.me"
  - "*.icetorrent.org"
  - "*.jpopsuki.eu"
  - "*.keepfrds.com"
  - "*.leaguehd.com"
  - "*.m-team.cc"
  - "*.madsrevolution.net"
  - "*.msg.vg"
  - "*.nanyangpt.com"
  - "*.ncore.cc"
  - "*.open.cd"
  - "*.ourbits.club"
  - "*.passthepopcorn.me"
  - "*.privatehd.to"
  - "*.pthome.net"
  - "*.redacted.ch"
  - "*.springsunday.net"
  - "*.tjupt.org"
  - "*.tju.pt"
  - "*.totheglory.im"
  - "*.trontv.com"
  - "*.teamviewer.com"
  - "*.baomitu.com"
  - "*.bootcss.com"
  - "*.jiasule.com"
  - "*.staticfile.org"
  - "*.upaiyun.com"
  - "*.10010.com"
  - "*.115.com"
  - "*.12306.com"
  - "*.17173.com"
  - "*.178.com"
  - "*.17k.com"
  - "*.360doc.com"
  - "*.36kr.com"
  - "*.3dmgame.com"
  - "*.51cto.com"
  - "*.51job.com"
  - "*.51jobcdn.com"
  - "*.56.com"
  - "*.8686c.com"
  - "*.abchina.com"
  - "*.abercrombie.com"
  - "*.acfun.tv"
  - "*.air-matters.com"
  - "*.air-matters.io"
  - "*.aixifan.com"
  - "*.algocasts.io"
  - "*.babytree.com"
  - "*.babytreeimg.com"
  - "*.baicizhan.com"
  - "*.baidupan.com"
  - "*.baike.com"
  - "*.biqudu.com"
  - "*.biquge.com"
  - "*.bitauto.com"
  - "*.c-ctrip.com"
  - "*.camera360.com"
  - "*.cdnmama.com"
  - "*.chaoxing.com"
  - "*.che168.com"
  - "*.chinacache.net"
  - "*.chinaso.com"
  - "*.chinaz.com"
  - "*.chinaz.net"
  - "*.chuimg.com"
  - "*.cibntv.net"
  - "*.clouddn.com"
  - "*.cloudxns.net"
  - "*.cn163.net"
  - "*.cnblogs.com"
  - "*.cnki.net"
  - "*.cnmstl.net"
  - "*.coolapk.com"
  - "*.coolapkmarket.com"
  - "*.csdn.net"
  - "*.ctrip.com"
  - "*.dangdang.com"
  - "*.dfcfw.com"
  - "*.dianping.com"
  - "*.dilidili.wang"
  - "*.douban.com"
  - "*.doubanio.com"
  - "*.dpfile.com"
  - "*.duowan.com"
  - "*.dxycdn.com"
  - "*.dytt8.net"
  - "*.easou.com"
  - "*.eastday.com"
  - "*.eastmoney.com"
  - "*.ecitic.com"
  - "*.ewqcxz.com"
  - "*.fang.com"
  - "*.fantasy.tv"
  - "*.feng.com"
  - "*.fengkongcloud.com"
  - "*.fir.im"
  - "*.frdic.com"
  - "*.fresh-ideas.cc"
  - "*.ganji.com"
  - "*.ganjistatic1.com"
  - "*.geetest.com"
  - "*.geilicdn.com"
  - "*.ghpym.com"
  - "*.godic.net"
  - "*.guazi.com"
  - "*.gwdang.com"
  - "*.gzlzfm.com"
  - "*.haibian.com"
  - "*.haosou.com"
  - "*.hollisterco.com"
  - "*.hongxiu.com"
  - "*.huajiao.com"
  - "*.hupu.com"
  - "*.huxiucdn.com"
  - "*.huya.com"
  - "*.ifeng.com"
  - "*.ifengimg.com"
  - "*.images-amazon.com"
  - "*.infzm.com"
  - "*.ipip.net"
  - "*.it168.com"
  - "*.ithome.com"
  - "*.ixdzs.com"
  - "*.jianguoyun.com"
  - "*.jianshu.com"
  - "*.jianshu.io"
  - "*.jianshuapi.com"
  - "*.jiathis.com"
  - "*.jmstatic.com"
  - "*.jumei.com"
  - "*.kaola.com"
  - "*.knewone.com"
  - "*.koowo.com"
  - "*.ksyungslb.com"
  - "*.kuaidi100.com"
  - "*.kugou.com"
  - "*.lancdns.com"
  - "*.landiannews.com"
  - "*.lanzou.com"
  - "*.lanzoui.com"
  - "*.lanzoux.com"
  - "*.lemicp.com"
  - "*.letitfly.me"
  - "*.lizhi.fm"
  - "*.lizhi.io"
  - "*.lizhifm.com"
  - "*.luoo.net"
  - "*.lvmama.com"
  - "*.lxdns.com"
  - "*.maoyan.com"
  - "*.meilishuo.com"
  - "*.meituan.com"
  - "*.meituan.net"
  - "*.meizu.com"
  - "*.migucloud.com"
  - "*.miguvideo.com"
  - "*.mobike.com"
  - "*.mogu.com"
  - "*.mogucdn.com"
  - "*.mogujie.com"
  - "*.moji.com"
  - "*.moke.com"
  - "*.msstatic.com"
  - "*.mubu.com"
  - "*.myunlu.com"
  - "*.nruan.com"
  - "*.nuomi.com"
  - "*.onedns.net"
  - "*.oneplus.com"
  - "*.onlinedown.net"
  - "*.oppo.com"
  - "*.oracle.com"
  - "*.oschina.net"
  - "*.ourdvs.com"
  - "*.polyv.net"
  - "*.qbox.me"
  - "*.qcloud.com"
  - "*.qcloudcdn.com"
  - "*.qdaily.com"
  - "*.qdmm.com"
  - "*.qhimg.com"
  - "*.qianqian.com"
  - "*.qidian.com"
  - "*.qihucdn.com"
  - "*.qin.io"
  - "*.qiniu.com"
  - "*.qiniucdn.com"
  - "*.qiniudn.com"
  - "*.qiushibaike.com"
  - "*.quanmin.tv"
  - "*.qunar.com"
  - "*.qunarzz.com"
  - "*.realme.com"
  - "*.repaik.com"
  - "*.ruguoapp.com"
  - "*.runoob.com"
  - "*.sankuai.com"
  - "*.segmentfault.com"
  - "*.sf-express.com"
  - "*.shumilou.net"
  - "*.simplecd.me"
  - "*.smzdm.com"
  - "*.snwx.com"
  - "*.soufunimg.com"
  - "*.sspai.com"
  - "*.startssl.com"
  - "*.suning.com"
  - "*.synology.com"
  - "*.taihe.com"
  - "*.th-sjy.com"
  - "*.tianqi.com"
  - "*.tianqistatic.com"
  - "*.tianyancha.com"
  - "*.tianyaui.com"
  - "*.tietuku.com"
  - "*.tiexue.net"
  - "*.tmiaoo.com"
  - "*.trip.com"
  - "*.ttmeiju.com"
  - "*.tudou.com"
  - "*.tuniu.com"
  - "*.tuniucdn.com"
  - "*.umengcloud.com"
  - "*.upyun.com"
  - "*.uxengine.net"
  - "*.videocc.net"
  - "*.vivo.com"
  - "*.wandoujia.com"
  - "*.weather.com"
  - "*.weico.cc"
  - "*.weidian.com"
  - "*.weiphone.com"
  - "*.weiphone.net"
  - "*.womai.com"
  - "*.wscdns.com"
  - "*.xdrig.com"
  - "*.xhscdn.com"
  - "*.xiachufang.com"
  - "*.xiaohongshu.com"
  - "*.xiaojukeji.com"
  - "*.xinhuanet.com"
  - "*.xip.io"
  - "*.xitek.com"
  - "*.xiumi.us"
  - "*.xslb.net"
  - "*.xueqiu.com"
  - "*.yach.me"
  - "*.yeepay.com"
  - "*.yhd.com"
  - "*.yihaodianimg.com"
  - "*.yinxiang.com"
  - "*.yinyuetai.com"
  - "*.yixia.com"
  - "*.ys168.com"
  - "*.yuewen.com"
  - "*.yy.com"
  - "*.yystatic.com"
  - "*.zealer.com"
  - "*.zhangzishi.cc"
  - "*.zhanqi.tv"
  - "*.zhaopin.com"
  - "*.zhihu.com"
  - "*.zhimg.com"
  - "*.zhongsou.com"
  - "*.zhuihd.com"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
